# Environment Configurations for OpenPortal
# Purpose: Environment-specific settings for compositions
# Applied by: config-openportal.sh after variable substitution
---
apiVersion: apiextensions.crossplane.io/v1beta1
kind: EnvironmentConfig
metadata:
  name: dns-config
  namespace: crossplane-system
data:
  zone: "${BASE_DOMAIN}"  # Used by templates for app URLs (localhost for local, openportal.dev for prod)
  provider: "external-dns"
---
apiVersion: apiextensions.crossplane.io/v1beta1
kind: EnvironmentConfig
metadata:
  name: cloudflare-config
  namespace: crossplane-system
data:
  zone_id: "${CLOUDFLARE_ZONE_ID}"
  account_id: "${CLOUDFLARE_ACCOUNT_ID}"