# Flux GitOps: Catalog Orders Watcher
# Purpose: Monitors and syncs XR instances created by Backstage templates
# Uses ${CURRENT_CONTEXT} environment variable to determine path
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: catalog-orders
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/open-service-portal/catalog-orders
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: catalog-orders
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: catalog-orders
  # Path based on current kubectl context
  path: "./${CURRENT_CONTEXT}"
  prune: true
  # Force mode: Continue applying resources even if some fail
  # This prevents a single error from blocking all other resources
  force: true
  # Important: XRs should be applied after XRDs from catalog
  dependsOn:
    - name: catalog
  # Retry on failure for resilience
  retryInterval: 30s