apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xapplications.example.io
spec:
  compositeTypeRef:
    apiVersion: example.io/v1alpha1
    kind: XApplication
  resources:
    - name: namespace
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: crossplane-app
      patches:
        - fromFieldPath: "spec.parameters.namespace"
          toFieldPath: "spec.forProvider.manifest.metadata.name"
          
    - name: deployment
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                namespace: default
              spec:
                replicas: 1
                selector:
                  matchLabels:
                    app: crossplane-app
                template:
                  metadata:
                    labels:
                      app: crossplane-app
                  spec:
                    containers:
                    - name: app
                      image: nginx:latest
                      ports:
                      - containerPort: 80
      patches:
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.forProvider.manifest.metadata.name"
          transforms:
            - type: string
              string:
                fmt: "app-%s"
        - fromFieldPath: "spec.parameters.namespace"
          toFieldPath: "spec.forProvider.manifest.metadata.namespace"
        - fromFieldPath: "spec.parameters.replicas"
          toFieldPath: "spec.forProvider.manifest.spec.replicas"
        - fromFieldPath: "spec.parameters.image"
          toFieldPath: "spec.forProvider.manifest.spec.template.spec.containers[0].image"
        - fromFieldPath: "spec.parameters.port"
          toFieldPath: "spec.forProvider.manifest.spec.template.spec.containers[0].ports[0].containerPort"
          
    - name: service
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Service
              metadata:
                namespace: default
              spec:
                type: ClusterIP
                selector:
                  app: crossplane-app
                ports:
                - port: 80
                  targetPort: 80
                  protocol: TCP
      patches:
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.forProvider.manifest.metadata.name"
          transforms:
            - type: string
              string:
                fmt: "svc-%s"
        - fromFieldPath: "spec.parameters.namespace"
          toFieldPath: "spec.forProvider.manifest.metadata.namespace"
        - fromFieldPath: "spec.parameters.serviceType"
          toFieldPath: "spec.forProvider.manifest.spec.type"
        - fromFieldPath: "spec.parameters.port"
          toFieldPath: "spec.forProvider.manifest.spec.ports[0].targetPort"