apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xapplications.example.io
spec:
  group: example.io
  names:
    kind: XApplication
    plural: xapplications
  claimNames:
    kind: Application
    plural: applications
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  namespace:
                    type: string
                    description: "Namespace to deploy the application"
                    default: "default"
                  image:
                    type: string
                    description: "Container image for the application"
                  replicas:
                    type: integer
                    description: "Number of replicas"
                    default: 1
                  port:
                    type: integer
                    description: "Container port"
                    default: 80
                  serviceType:
                    type: string
                    description: "Service type (ClusterIP, NodePort, LoadBalancer)"
                    default: "ClusterIP"
                    enum:
                    - ClusterIP
                    - NodePort
                    - LoadBalancer
                required:
                - image
            required:
            - parameters