apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: backstage-namespace
  namespace: default
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: backstage
        labels:
          app: backstage
          environment: development
          managed-by: crossplane
  providerConfigRef:
    name: kubernetes-provider