apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: postgres-secret
  namespace: default
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Secret
      metadata:
        name: postgres-credentials
        namespace: backstage
      type: Opaque
      data:
        # These are base64 encoded values - for demo only
        # In production, use external secret management
        POSTGRES_USER: YmFja3N0YWdl # backstage
        POSTGRES_PASSWORD: Y2hhbmdlbWUxMjM= # changeme123
        POSTGRES_DB: YmFja3N0YWdlX2Ri # backstage_db
  providerConfigRef:
    name: kubernetes-provider
  references:
    # This ensures the namespace exists before creating the secret
    - patchesFrom:
        apiVersion: kubernetes.crossplane.io/v1alpha2
        kind: Object
        name: backstage-namespace
        namespace: default
        fieldPath: metadata.uid
      toFieldPath: metadata.annotations[crossplane.io/dependency]