apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: service-config
  namespace: default
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: service-catalog-config
        namespace: backstage
      data:
        catalog-locations.yaml: |
          catalog:
            locations:
              # GitHub discovery
              - type: github-discovery
                target: https://github.com/open-service-portal/service-*/blob/main/catalog-info.yaml
              
              # Template locations
              - type: url
                target: https://github.com/open-service-portal/service-nodejs-template/blob/main/template.yaml
              - type: url
                target: https://github.com/open-service-portal/service-golang-template/blob/main/template.yaml
              - type: url
                target: https://github.com/open-service-portal/service-python-template/blob/main/template.yaml
        
        integrations.yaml: |
          integrations:
            github:
              - host: github.com
                token: ${GITHUB_TOKEN}
            gitlab:
              - host: gitlab.com
                token: ${GITLAB_TOKEN}
  providerConfigRef:
    name: kubernetes-provider