# Backstage Service Account Token Secret
# Purpose: Persistent token for Backstage to authenticate with Kubernetes
# Applied by: setup-cluster.sh (conditionally if not exists)
apiVersion: v1
kind: Secret
metadata:
  name: backstage-k8s-sa-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: backstage-k8s-sa
    description: "Persistent token for Backstage - shared by team"
type: kubernetes.io/service-account-token