# Crossplane Provider Cloudflare
# Purpose: Enables management of Cloudflare resources (DNS, Workers, etc.)
# Restaurant Analogy: The "supplier" that provides DNS hosting services
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-cloudflare
  annotations:
    crossplane.io/version: "v2.0"
    description: "Cloudflare provider for DNS and CDN management"
spec:
  # Using cdloh provider-cloudflare (Upjet-based)
  # This provider uses Terraform Cloudflare provider under the hood
  package: ghcr.io/cdloh/provider-cloudflare:v0.1.0

# NOTE: The ProviderConfig will be created after the CRDs are installed
# The secret is created by the config-openportal.sh script
# 
# To configure Cloudflare credentials:
# 1. Copy .env.openportal.example to .env.openportal
# 2. Add your Cloudflare API token and IDs to .env.openportal
# 3. Run: ./scripts/config-openportal.sh
#
# The script will:
# - Create the cloudflare-credentials secret
# - Import the Zone resource
# - Configure environment configs
#
# How to get the Cloudflare token:
# 1. Go to https://dash.cloudflare.com/profile/api-tokens
# 2. Create Token → Use "Edit zone DNS" template
# 3. Set permissions: Zone:DNS:Edit for your specific zone
# 4. Add the token to .env.openportal as CLOUDFLARE_USER_API_TOKEN
