# Cloudflare Provider Configuration
# Purpose: Configure the Cloudflare provider with credentials
# Applied by: config-openportal.sh (references secret created by the script)
apiVersion: cloudflare.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: cloudflare-provider
spec:
  credentials:
    source: Secret
    secretRef:
      name: cloudflare-credentials
      namespace: crossplane-system
      key: credentials