---
# ClusterRoleBinding for Cluster Admin User
# Template variables: USER_EMAIL, BINDING_NAME
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${BINDING_NAME}
  labels:
    rbac.openportal.dev/type: explicit-admin
    rbac.openportal.dev/managed-by: rbac-add-admin
  annotations:
    rbac.openportal.dev/description: "Cluster admin access for ${USER_EMAIL}"
    rbac.openportal.dev/created-at: "${CREATED_AT}"
subjects:
- kind: User
  name: "oidc:${USER_EMAIL}"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
