---
# Namespace for User
# Template variables: NAMESPACE, USER_EMAIL, USERNAME, CREATED_AT
apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
  labels:
    name: ${NAMESPACE}
    rbac.openportal.dev/owner: "${USERNAME}"
    rbac.openportal.dev/managed-by: rbac-add-namespace-access
  annotations:
    rbac.openportal.dev/description: "Namespace for ${USER_EMAIL}"
    rbac.openportal.dev/created-at: "${CREATED_AT}"

---
# RoleBinding for Namespace Access
# Template variables: BINDING_NAME, NAMESPACE, USER_EMAIL, USERNAME, ROLE, CREATED_AT
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${BINDING_NAME}
  namespace: ${NAMESPACE}
  labels:
    rbac.openportal.dev/type: namespace-scoped
    rbac.openportal.dev/managed-by: rbac-add-namespace-access
  annotations:
    rbac.openportal.dev/description: "${ROLE} access for ${USER_EMAIL} in ${NAMESPACE} namespace"
    rbac.openportal.dev/created-at: "${CREATED_AT}"
subjects:
- kind: User
  name: "oidc:${USER_EMAIL}"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: ${ROLE}
  apiGroup: rbac.authorization.k8s.io
