#!/bin/bash
# Generic cluster configuration script
# Automatically detects cluster and applies appropriate configuration

set -e

# Script directories
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$(dirname "$SCRIPT_DIR")"
MANIFEST_DIR="${SCRIPT_DIR}/manifests-config"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get current kubectl context
CURRENT_CONTEXT=$(kubectl config current-context 2>/dev/null || echo "")

if [ -z "$CURRENT_CONTEXT" ]; then
    echo -e "${RED}Error: No kubectl context selected${NC}"
    echo "Available contexts:"
    kubectl config get-contexts
    echo ""
    echo "Usage: kubectl config use-context <context-name> && $0"
    exit 1
fi

echo -e "${BLUE}================================${NC}"
echo -e "${BLUE}   Cluster Configuration Tool${NC}"
echo -e "${BLUE}================================${NC}"
echo ""
echo "Current context: ${GREEN}${CURRENT_CONTEXT}${NC}"

# Find environment file
ENV_FILE=""

# Try to find environment file for this context
if [ -f "$WORKSPACE_DIR/.env.${CURRENT_CONTEXT}" ]; then
    ENV_FILE=".env.${CURRENT_CONTEXT}"
elif [ -f "$WORKSPACE_DIR/.env.openportal" ] && [[ "$CURRENT_CONTEXT" == *openportal* ]]; then
    # Backward compatibility for .env.openportal
    ENV_FILE=".env.openportal"
elif [ -f "$WORKSPACE_DIR/.env.local" ] && [[ "$CURRENT_CONTEXT" =~ (docker-desktop|rancher-desktop|minikube|kind) ]]; then
    # Backward compatibility for .env.local
    ENV_FILE=".env.local"
else
    echo -e "${YELLOW}No environment file found for context: ${CURRENT_CONTEXT}${NC}"
    echo ""
    echo "Expected file: .env.${CURRENT_CONTEXT}"
    echo ""
    echo "You can create it from an example:"
    echo "  cp .env.rancher-desktop.example .env.${CURRENT_CONTEXT}"
    echo "  vim .env.${CURRENT_CONTEXT}"
    echo ""
    echo "Or use a specific config script:"
    echo "  ./scripts/cluster-config-local.sh      # For local development"
    echo "  ./scripts/cluster-config-openportal.sh # For OpenPortal production"
    exit 1
fi

echo "Using environment file: ${GREEN}${ENV_FILE}${NC}"
echo ""

# Load environment variables
if [ -f "$WORKSPACE_DIR/$ENV_FILE" ]; then
    set -a  # Auto-export all variables
    source "$WORKSPACE_DIR/$ENV_FILE"
    set +a  # Turn off auto-export
    echo "✓ Loaded $ENV_FILE"
else
    echo -e "${RED}Error: Environment file not found: $ENV_FILE${NC}"
    echo "Please create it from the example:"
    echo "  cp ${ENV_FILE}.example $ENV_FILE"
    echo "  vim $ENV_FILE"
    exit 1
fi

# Note: CLUSTER_NAME is no longer needed in env files when using config.sh
# The kubectl context IS the cluster name

# =============================================================================
# Common Functions
# =============================================================================

# Update Backstage configuration
update_backstage_config() {
    echo ""
    echo "Configuring Backstage for cluster: $CURRENT_CONTEXT"
    
    # Check if app-portal directory exists
    if [ ! -d "$WORKSPACE_DIR/app-portal" ]; then
        echo -e "${YELLOW}Warning: app-portal directory not found${NC}"
        echo "Clone the app-portal repository first:"
        echo "  git clone https://github.com/open-service-portal/app-portal.git"
        return 1
    fi
    
    # Get token from cluster
    SECRET_NAME="backstage-k8s-sa-token"
    TOKEN=$(kubectl get secret $SECRET_NAME -n default -o jsonpath='{.data.token}' 2>/dev/null | base64 -d)
    
    if [ -z "$TOKEN" ]; then
        echo -e "${RED}Error: No Backstage token found in cluster${NC}"
        echo "Run setup-cluster.sh first to create the service account:"
        echo "  ./scripts/setup-cluster.sh"
        return 1
    fi
    
    # Get cluster information
    K8S_API_URL=$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}')
    K8S_CLUSTER_NAME=$(kubectl config current-context)
    
    # Create config file named after the context with .local.yaml suffix
    CONFIG_FILE="app-config.${CURRENT_CONTEXT}.local.yaml"
    APP_TITLE="Backstage (${CURRENT_CONTEXT})"
    
    # Create/update Backstage config
    cat > "$WORKSPACE_DIR/app-portal/$CONFIG_FILE" <<EOF
# Cluster configuration - auto-generated by cluster-config.sh
# DO NOT EDIT MANUALLY - Run cluster-config.sh to regenerate

app:
  title: $APP_TITLE
  baseUrl: http://localhost:3000

backend:
  baseUrl: http://localhost:7007

kubernetes:
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: $K8S_API_URL
          name: $K8S_CLUSTER_NAME
          authProvider: 'serviceAccount'
          skipTLSVerify: true
          serviceAccountToken: $TOKEN
EOF
    
    echo -e "${GREEN}✓ Created app-portal/$CONFIG_FILE${NC}"
}

# Configure Flux for catalog-orders
configure_flux_catalog_orders() {
    echo ""
    echo "Configuring Flux to watch catalog-orders for cluster: ${CURRENT_CONTEXT}"
    
    # Check if Flux is installed
    if ! kubectl get namespace flux-system &>/dev/null; then
        echo -e "${YELLOW}Flux is not installed on this cluster${NC}"
        return 1
    fi
    
    # Apply catalog-orders configuration with environment substitution
    if envsubst < "$MANIFEST_DIR/flux-catalog-orders.yaml" | kubectl apply -f -; then
        echo -e "${GREEN}✓ Flux configured to watch catalog-orders${NC}"
        
        # Force reconciliation
        flux reconcile source git catalog-orders 2>/dev/null || true
    else
        echo -e "${YELLOW}Note: Could not configure catalog-orders${NC}"
    fi
}

# Configure External-DNS (if applicable)
configure_external_dns() {
    echo ""
    echo "Checking External-DNS configuration..."
    
    # Check if External-DNS is installed
    if ! kubectl get namespace external-dns &>/dev/null; then
        echo -e "${YELLOW}External-DNS is not installed${NC}"
        return 1
    fi
    
    # Check for Cloudflare credentials
    if [ -n "$CLOUDFLARE_API_TOKEN" ] && [ "$CLOUDFLARE_API_TOKEN" != "your-api-token-here" ]; then
        echo "Creating Cloudflare API token secret for External-DNS..."
        kubectl create secret generic cloudflare-api-token \
            --from-literal=cloudflare_api_token="${CLOUDFLARE_API_TOKEN}" \
            --namespace external-dns \
            --dry-run=client -o yaml | kubectl apply -f -
        
        echo "✓ Cloudflare credentials configured for External-DNS"
        echo "  External-DNS will create real DNS records in Cloudflare"
        echo "  Zone: ${CLOUDFLARE_ZONE_NAME:-openportal.dev}"
    else
        echo -e "${YELLOW}Note: No Cloudflare credentials configured${NC}"
        echo "  External-DNS will run but cannot create DNS records"
    fi
    
    # Update EnvironmentConfig if needed
    if [ -n "$BASE_DOMAIN" ]; then
        echo "Updating dns-config EnvironmentConfig..."
        kubectl patch environmentconfig dns-config \
            --type merge \
            --patch "{\"data\": {\"zone\": \"${BASE_DOMAIN}\"}}" \
            2>/dev/null || echo "  Note: EnvironmentConfig not found"
    fi
}

# Update EnvironmentConfigs (if manifest exists and variables are set)
update_environment_configs() {
    if [ -f "$MANIFEST_DIR/environment-configs.yaml" ] && [ -n "$BASE_DOMAIN" ]; then
        echo ""
        echo "Updating EnvironmentConfigs..."
        envsubst < "$MANIFEST_DIR/environment-configs.yaml" | kubectl apply -f -
        echo "✓ EnvironmentConfigs updated"
    fi
}

# =============================================================================
# Main Execution
# =============================================================================

echo -e "${BLUE}Starting configuration...${NC}"
echo ""

# Run common configurations
update_backstage_config
configure_flux_catalog_orders
configure_external_dns
update_environment_configs

# Summary
echo ""
echo -e "${GREEN}================================${NC}"
echo -e "${GREEN}   Configuration Complete!${NC}"
echo -e "${GREEN}================================${NC}"
echo ""
echo "Cluster: ${CURRENT_CONTEXT}"
echo "Config: ${ENV_FILE}"

if [ -n "$BASE_DOMAIN" ]; then
    echo "Base Domain: ${BASE_DOMAIN}"
fi

if [ -n "$CLOUDFLARE_ZONE_NAME" ]; then
    echo "Cloudflare Zone: ${CLOUDFLARE_ZONE_NAME}"
fi

echo ""
echo "To start Backstage:"
echo "  cd app-portal"
echo "  yarn start  # Check package.json for context-specific scripts"

echo ""
echo -e "${GREEN}Done!${NC}"